### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by ghost** [spaceflint7/bluebonnet#1]
It's 3 years without a new commit. Please make it clear on README.md whether it's still being developed or not. Thank you.

**Comment by spaceflint7** [comment]
Sorry for the late reply.  I appreciate your interest in this project!  Sorry to say that I am not currently actively developing this project further.  My focus at this time is the JavaScript-to-C compiler project that I'm writing.  (Available in a nearby repository.)
